### ISSUE TITLE
[splunk] Maj 5.8.x error

### ISSUE THREAD

**Issue by Tonnulus** [OpenCTI-Platform/connectors#1251]
## Description

The connector is not working since 5.8.2 update.

```
{"timestamp": "2023-06-22T09:34:34.747245Z", "level": "ERROR", "name": "pycti.connector", "message": "an error occurred while consuming messages"}
{"timestamp": "2023-06-22T09:34:34.747362Z", "level": "ERROR", "name": "pycti.connector", "message": "'OpenCTIConnectorHelper' object has no attribute 'get_stream_name'"}
```

## Environment

1. Debian 11
2. OpenCTI version: 5.8.2
3. OpenCTI connector: 5.8.2
4. Other environment details:

## Reproducible Steps

My configuration

```
    opencti_connector_splunk:
      image: opencti/connector-splunk:{{ opencti.version }}
      env:
        "OPENCTI_URL": "http://opencti:8080/opencti"
        "OPENCTI_SSL_VERIFY": "false"
        "OPENCTI_TOKEN": "{{ opencti_connector_splunk.opencti_token }}"
        "CONNECTOR_ID": "{{ opencti_connector_splunk.connector_id }}"
        "CONNECTOR_LIVE_STREAM_ID": "{{ opencti_connector_splunk.live_stream_id }}"
        "CONNECTOR_NAME": "{{ opencti_connector_splunk.name }}"
        "CONNECTOR_TYPE": "STREAM"
        "CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES": "true"
        "CONNECTOR_LIVE_STREAM_LISTEN_DELETE": "true"
        "CONNECTOR_SCOPE": "splunk"
        "CONNECTOR_CONFIDENCE_LEVEL": "80"
        "CONNECTOR_LOG_LEVEL": "info"
        "SPLUNK_URL": "{{ opencti_connector_splunk.splunk_url }}"
        "SPLUNK_TOKEN": "{{ opencti_connector_splunk.splunk_token }}"
        "SPLUNK_OWNER":  "{{ opencti_connector_splunk.splunk_owner }}"
        "SPLUNK_APP": "{{ opencti_connector_splunk.splunk_app }}"
        "SPLUNK_KV_STORE_NAME": "{{ opencti_connector_splunk.splunk_kvstore }}"
        "SPLUNK_SSL_VERIFY": "false"
        "SPLUNK_IGNORE_TYPES": "label,marking-definition,identity,label,external-reference"
        "CONNECTOR_CONSUMER_COUNT": "{{ opencti_connector_splunk.consumers }}"
      networks:
        - name: back
 ```
## Additional information

It was working with this version https://github.com/OpenCTI-Platform/connectors/pull/1145 and opencti 5.7.4.
