### ISSUE TITLE
Error when running Mandiant Connector: "Object of type datetime is not JSON serializable"

### ISSUE THREAD

**Issue by emiltmadsen** [OpenCTI-Platform/connectors#1316]
## Description

When trying to use the Mandiant Connector with default settings apart from changing "MANDIANT_IMPORT_START_DATE" I receive a TypeError.

## Environment

1. OS (where OpenCTI server runs): Pop!_OS 22.04 LTS
2. OpenCTI version: OpenCTI 5.9.6
3. OpenCTI client: docker-compose / frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Use the following connector setup in docker-compose.yml

```
  connector-mandiant-advantage:
    image: opencti/connector-mandiant:5.9.6
    environment:
        OPENCTI_URL: http://opencti:8080
        OPENCTI_TOKEN: <redacted>
        CONNECTOR_ID: <redacted>
        CONNECTOR_TYPE: EXTERNAL_IMPORT
        CONNECTOR_NAME: Mandiant
        CONNECTOR_SCOPE: mandiant
        CONNECTOR_CONFIDENCE_LEVEL: 15
        CONNECTOR_UPDATE_EXISTING_DATA: "false"
        CONNECTOR_LOG_LEVEL: info
        MANDIANT_API_URL: https://api.intelligence.mandiant.com/
        MANDIANT_API_V4_KEY_ID: <redacted>
        MANDIANT_API_V4_KEY_SECRET: <redacted>
        MANDIANT_INTERVAL: 1 # Number of days between collection
        MANDIANT_IMPORT_START_DATE: 2023-07-25T00:00:00.00Z
        MANDIANT_INDICATOR_MINIMUM_SCORE: 80
        MANDIANT_IMPORT_ACTORS: "True"
        MANDIANT_IMPORT_REPORTS: "True"
        MANDIANT_IMPORT_MALWARES: "True"
        MANDIANT_IMPORT_CAMPAIGNS: "True"
        MANDIANT_IMPORT_INDICATORS: "True"
        MANDIANT_IMPORT_VULNERABILITIES: "True"
        MANDIANT_ACTOR_PROFILE_REPORT: "True"
        MANDIANT_COUNTRY_PROFILE_REPORT: "True"
        MANDIANT_EVENT_COVERAGE_IMPLICATION_REPORT: "True"
        MANDIANT_EXECUTIVE_PERSPECTIVE_REPORT: "True"
        MANDIANT_ICS_SECURITY_ROUNDUP_REPORT: "True"
        MANDIANT_INDUSTRY_REPORTING_REPORT: "True"
        MANDIANT_MALWARE_PROFILE_REPORT: "True"
        MANDIANT_NETWORK_ACTIVITY_REPORT: "True"
        MANDIANT_PATCH_REPORT: "True"
        MANDIANT_TTP_DEEP_DIVE_REPORT: "True"
        MANDIANT_THREAT_ACTIVITY_ALERT_REPORT: "True"
        MANDIANT_THREAT_ACTIVITY_REPORT: "True"
        MANDIANT_TRENDS_AND_FORECASTING_REPORT: "True"
        MANDIANT_VULNERABILITY_REPORT: "True"
        MANDIANT_WEEKLY_VULNERABILITY_EXPLOITATION_REPORT: "True"
        MANDIANT_NEWS_ANALYSIS_REPORT: "True"
```

2. Start OpenCTI via. docker-compose

## Expected Output

I expected OpenCTI to start and the connector to establish contact with Mandiant and retrieve the corresponding data and update OpenCTI objects accordingly.

## Actual Output

I get the following TypeError: "Object of type datetime is not JSON serializable" (see screenshot for Traceback).

## Additional information

I tried using an EPOCH Timestamp instead, which let me start OpenCTI but I received no data from Mandiant. When reviewing my docker logs I got the following error "time data '1690286400' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'".
According to the documentation the default is "2023-01-01", there is no explanation for what type of time is used (EPOCH vs ISO format). I suggest that the correct format is added to the documentation (2023-01-01T00:00:00.00Z).

## Screenshots (optional)
![screenshot png](https://github.com/OpenCTI-Platform/connectors/assets/61865338/1b7f5749-a3a6-4ba9-b49b-9498cad915c9)
