### ISSUE TITLE
[CrowndStrike] - error: (403) access denied, authorization failed

### ISSUE THREAD

**Issue by TlcTac** [OpenCTI-Platform/connectors#139]
## Description
I'm integrating the CorwdStrike connector to the OpenCTI platform, but it's not working.
Indeed, even though I modified the docker file,  I get the following logs from the CrowdStrike container :
``` bash
INFO:crowdstrike_client.http.client:Unauthenticated, trying to reauthenticate...
INFO:crowdstrike_client.api.authenticator:Generated access token (type 'bearer') expires in 1799 seconds
ERROR:crowdstrike_client.api.utils:Request to 'https://api.crowdstrike.com/intel/combined/indicators/v1?offset=0&limit=10000&sort=published_date%7Cdesc&filter=published_date%3A%3E1588749630%2Btype%3A%21%5B%27hash_ion%27%2C+%27hash_md5...' failed with HTTP 403
ERROR:crowdstrike_client.api.utils:Failed request meta trace id: d000ce63-0424-4b31-8205-xxxxxxxxxxxx, query time: 0.042136472, powered by: crowdstrike-api-gateway
ERROR:crowdstrike_client.api.utils:Failed request error: (403) access denied, authorization failed
ERROR:root:API call failed with status code 403
```

## Environment

1. OS : Linux Mint 19.1 Tessa
2. OpenCTI version: OpenCTI 3.2.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add the CrowdStrike container to the docker-compose
2. Create the OAuth2 API Clients
3. Change the client API rights
4. run docker

## Additional information
I have rewritten the docker-composite proposed in the connector by completing it with the CLIENT_SECRET and CLIENT_ID provided by my CrowdStrike account.
The identifiers that are available here :
![image](https://user-images.githubusercontent.com/32235552/81796630-ff62cd00-950d-11ea-9162-e8ea3404971b.png)
I did, however, modify the client's rights :
![image](https://user-images.githubusercontent.com/32235552/81797039-8c0d8b00-950e-11ea-8854-78f7a7d51e53.png)

Here you can see my CrowdStrike container (in the docker-composite.yml)
``` yml
  connector-crowdstrike:
    image: opencti/connector-crowdstrike:3.2.1
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_CROWSTRIKE_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=CrowdStrike
      - CONNECTOR_SCOPE=crowdstrike
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - CROWDSTRIKE_BASE_URL=https://api.crowdstrike.com
      - CROWDSTRIKE_CLIENT_ID=05c[...]
      - CROWDSTRIKE_CLIENT_SECRET=O2n[...]
      - CROWDSTRIKE_TLP=amber
      - CROWDSTRIKE_SCOPES=actor,report,indicator,yara_master
      - CROWDSTRIKE_ACTOR_START_TIMESTAMP=1588749630
      - CROWDSTRIKE_REPORT_START_TIMESTAMP=1588749630 # BEWARE! A lot of reports!
      - CROWDSTRIKE_REPORT_STATUS=New
      - CROWDSTRIKE_REPORT_INCLUDE_TYPES=notice,tipper,intelligence report,periodic report
      - CROWDSTRIKE_REPORT_TYPE=Threat Report
      - CROWDSTRIKE_REPORT_GUESS_MALWARE=false # Use report tags to guess malware
      - CROWDSTRIKE_INDICATOR_START_TIMESTAMP=1588749630 # BEWARE! A lot of indicators!
      - CROWDSTRIKE_INDICATOR_EXCLUDE_TYPES=hash_ion,hash_md5,hash_sha1
      - CROWDSTRIKE_INTERVAL_SEC=600
    restart: always
```
Do you have an idea? Thank you for your help
