### ISSUE TITLE
[MISP Connector] Ignoring Filter but code seems to be fine

### ISSUE THREAD

**Issue by andurin** [OpenCTI-Platform/connectors#151]
## Description

While using the latest (docker rolling) MISP Connector and also previous ones the MISP Connector / PyMISP seems to ignore the filter.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 16
2. OpenCTI version: OpenCTI 3.2.2
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

MISP Connector Config:
```
opencti:
  url: 'http://opencti:8080'
  token: '39b00560-0227-11ea-9642-3bfaf2197c25'

connector:
  id: '39b00560-0227-11ea-9642-3bfaf21xxxxxx'
  type: 'EXTERNAL_IMPORT'
  name: 'MISP' # Required
  scope: 'misp'
  confidence_level: 3
  log_level: 'info'
  update_existing_data: False

misp:
  url: 'http://misp.example' # Required
  key: 'MY_VERY_SECRET_API_KEY # Required
  ssl_verify: False
  report_class: 'MISP event' # Optional, report_class if creating report for event
  create_reports: True # Required, create report for MISP event
  import_tags: 'OpenCTI: Import'
  interval: 1 # Minutes
  import_threat_levels: '1,2,3,4'

```

Log Output:
```
opencti_connector-misp.1.ovpuxjapz0v6@hiddenserver    | INFO:root:Fetching MISP events with args: {"tags": {"OR": ["OpenCTI: Import"]}, "timestamp": "2020-05-27 14:02:26", "limit": 50, "page": 1}
opencti_connector-misp.1.ovpuxjapz0v6@hiddenserver    | INFO:root:MISP returned 945 events.
opencti_connector-misp.1.ovpuxjapz0v6@hiddenserver    | INFO:root:Fetching MISP events with args: {"tags": {"OR": ["OpenCTI: Import"]}, "timestamp": "2020-05-27 14:02:26", "limit": 50, "page": 2}
opencti_connector-misp.1.ovpuxjapz0v6@hiddenserver    | INFO:root:MISP returned 945 events.
opencti_connector-misp.1.ovpuxjapz0v6@hiddenserver    | INFO:root:Fetching MISP events with args: {"tags": {"OR": ["OpenCTI: Import"]}, "timestamp": "2020-05-27 14:02:26", "limit": 50, "page": 3}
opencti_connector-misp.1.ovpuxjapz0v6@hiddenserver    | INFO:root:MISP returned 945 events.
```

## Expected Output

1. I only have 3 Events with the wished Tag
2. The pagination of 50 shouldn't show more than 50 Events
3. I sadly guess the connector will process 945 Events in `page` times ?!?!

## Additional information

I've extracted the code used by the connector, like using expanded pymisp, building the kwargs dict, using `misp.search()` etc. and it works fine but not as the connector is doing. I really can't explain where some difference may be.

As soon I'm using this code within the misp-connector docker container it shows me only my 3 Events. So I would assume this behavior has nothing to do with Python Version, PyMISP Version etc.

```
from pymisp import ExpandedPyMISP
import json
import urllib3
urllib3.disable_warnings()

misp_url = 'https://misp.example.com'
misp_key = 'YOUR_MISP_API_KEY'
misp_verifycert = False

misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, debug=False)

misp_import_tags = 'OpenCTI: Import'

kwargs = dict()
complex_query_tag = None
if misp_import_tags is not None:
    or_parameters = []
    for tag in misp_import_tags.split(","):
        or_parameters.append(tag.strip())
        complex_query_tag = misp.build_complex_query(
            or_parameters=or_parameters
        )

print("Complex_query_tag => {}".format(complex_query_tag))

if complex_query_tag is not None:
    kwargs["tags"] = complex_query_tag

current_page=1
kwargs["limit"] = 50
kwargs["page"] = current_page
print(
    "Fetching MISP events with args: " + json.dumps(kwargs)
)

events = []
try:
    events = misp.search("events", **kwargs)
except Exception as e:
    print(str(e))
    try:
        events = misp.search("events", **kwargs)
    except Exception as e:
        print(str(e))

print("MISP returned " + str(len(events)) + " events.")
```

Any help is appreciated to find the cause for my strange issue.
