### ISSUE TITLE
[IPQS] Terminated (does not register)

### ISSUE THREAD

**Issue by dominictory** [OpenCTI-Platform/connectors#1821]
IPQS connector does not register with OpenCTI v5.12.28.

```
INFO Health check (me)... | timestamp=2024-02-15T13:02:09.167035Z name=api
INFO Health check (me)... | timestamp=2024-02-15T13:02:09.719353Z name=api
Terminated
```

Using config:

```
connector-ipqs:
    image: opencti/connector-ipqs:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=https://opencti
      - OPENCTI_TOKEN=20031a3c-0fd9-406f-bec6-0063ed84dd4f
      - CONNECTOR_ID=8fb738a4-764d-48d4-b3b8-5b49f3e7fe07
      - CONNECTOR_NAME=IPQS Fraud and Risk Scoring
      - CONNECTOR_SCOPE=Domain-Name,IPv4-Addr,Email-Addr,Url,Phone-Number
      - CONNECTOR_AUTO=true
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
      - IPQS_PRIVATE_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - IPQS_BASE_URL=https://ipqualityscore.com/api/json
      # IP specific config settings
      - IPQS_IP_ADD_RELATIONSHIPS=true # Whether or not to add ASN relationships
      # Domain specific config settings
      - IPQS_DOMAIN_ADD_RELATIONSHIPS=true # Whether or not to add IP resolution relationships
    restart: always
```
