### ISSUE TITLE
Recorded Future Connector Crashing 

### ISSUE THREAD

**Issue by PeeBee66** [OpenCTI-Platform/connectors#1856]
The OpenCTI connector for Recorded Future is crashing due to a ValueError while attempting to convert a non-integer value to an integer.

**Environment**
OS (where OpenCTI server runs): Ubuntu, Docker
OpenCTI version:  OpenCTI 5.12.33
OpenCTI client: python 
Other environment details: Docker container

**Reproducible Steps**
Steps to create the smallest reproducible scenario:
1. Execute the OpenCTI connector for Recorded Future.
```
  connector-recordedfuture-feed:
    image: opencti/connector-recorded-future:${OPENCTI_VERSION}
    logging:
      driver: loki
      options:
        loki-url: "http://172.21.32.179:3100/loki/api/v1/push"
    environment:
      - OPENCTI_URL=http://opencti:4001
      - OPENCTI_TOKEN=${CONNECTOR_RF_USER}
      - CONNECTOR_ID=${CONNECTOR_RF_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME="Recorded Future Feed"
      - CONNECTOR_SCOPE=ipv4-addr,ipv6-addr,vulnerability,domain,url,StixFile
      - CONNECTOR_CONFIDENCE_LEVEL=25 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_UPDATE_EXISTING_DATA=True  
      - RECORDED_FUTURE_TOKEN=XXXX
      - RECORDED_FUTURE_INITIAL_LOOKBACK=240 
      - RECORDED_FUTURE_INTERVAL=12
      # RECORDED_FUTURE_TOPIC=ChangeMe #optional
      - RECORDED_FUTURE_TLP=White # required 
      - RECORDED_FUTURE_INSIKT_ONLY=False 
      - RECORDED_FUTURE_PULL_SIGNATURES=True #optional,
      - RECORDED_FUTURE_PERSON_TO_TA=False #optional,
      - RECORDED_FUTURE_TA_TO_INTRUSION_SET=False #optional, 
      - RECORDED_FUTURE_RISK_AS_SCORE=True #optional
      - RECORDED_FUTURE_RISK_THRESHOLD=60 #optiona
      - RECORDED_FUTURE_PULL_RISK_LIST=True #optional
      - RECORDED_FUTURE_RISK_LIST_INTERVAL=12 #required
      - RECORDED_FUTURE_RISK_LIST_THRESHOLD=70 #optional
      - RECORDED_FUTURE_RISKLIST_RELATED_ENTITIES='Malware,Hash,URL,Threat Actor,MitreAttackIdentifier' #required
      - RECORDED_FUTURE_PULL_THREAT_MAPS=True #optional
      - RECORDED_FUTURE_THREAT_MAPS_INTERVAL=12 #required
    restart: always
    depends_on:
      - opencti

```

2. After execution and the connectors been running for 30 min , encounter a row with a non-integer value in the "Risk" field.
3. The connector attempts to convert this value to an integer, resulting in a ValueError.
   
**Expected Output**
It continue to runs and not stop
The connector should gracefully handle non-integer values in the "Risk" field without crashing.

Actual Output
See image

The connector crashes with the following error message:
![image](https://github.com/OpenCTI-Platform/connectors/assets/129349395/d67fb236-f910-4878-badc-a9fa250e8651)
