### ISSUE TITLE
[dnstwist] Connector terminated

### ISSUE THREAD

**Issue by dominictory** [OpenCTI-Platform/connectors#1926]
dnstwist connector never registers in OpenCTI v6.0.5. Logs just state 'terminated'. 

Config:

```
connector-dnstwist:
    image: opencti/connector-dnstwist:${OPENCTI_VERSION}
    environment:
      - CONNECTOR_NAME=dnstwist
      - CONNECTOR_SCOPE=Domain-Name
      # Connector's generic execution parameters:
      - OPENCTI_URL=https://opencti
      - OPENCTI_TOKEN=85e37fbf-6904-4085-ad49-c78ee9ceefe0 ## connector token
      - CONNECTOR_ID=ff94d4fd-5ce0-47d9-ac9c-48afe368b12d # UUID of the connector
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted).
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_AUTO=false # don't run the connector automatically, you will flood your opencti instance
      - CONNECTOR_FETCH_REGISTERED=true # takes true or false; gives the ability to control the dnstwister domain selection
      - CONNECTOR_DNS_TWIST_THREADS=80 #number of threads to use for dnstwist; default is 20
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      # Connector's custom execution parameters:
      - EXTRA_PARAMETER=--nameservers 1.1.1.1
    restart: always
```

`OPENCTI_VERSION=6.0.5`
