### ISSUE TITLE
[diode-import] Question about creator and update of existing data

### ISSUE THREAD

**Issue by PeeBee66** [OpenCTI-Platform/connectors#2179]
**Prerequisites**

- [X] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview/) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting/) page and didn't find anything relevant to my problem.
- [X] I went through old GitHub issues and couldn't find anything relevant.
- [X] I googled the issue and didn't find anything relevant.

**Description**

Background: I have each feed pulling in data as per the connector example for MITRE and it save's the output to the .JSON files.

```
  connector-mitre:
    image: opencti/connector-mitre:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_ID}
      - "CONNECTOR_NAME=MITRE Datasets"
      - CONNECTOR_SCOPE=tool,report,malware,identity,campaign,intrusion-set,attack-pattern,course-of-action,x-mitre-data-source,x-mitre-data-component,x-mitre-matrix,x-mitre-tactic,x-mitre-collection
      - CONNECTOR_CONFIDENCE_LEVEL=75
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_REMOVE_STATEMENT_MARKING=true
      - MITRE_INTERVAL=2
      - CONNECTOR_SEND_TO_QUEUE=true
      - CONNECTOR_SEND_TO_DIRECTORY=true
      - CONNECTOR_SEND_TO_DIRECTORY_PATH=/data
      - CONNECTOR_SEND_TO_DIRECTORY_RETENTION=1
    restart: always
    volumes:
      - type: bind
        source: "/mnt/connector/8.Test-Backup/c.mitre"
        target: /data
```
Each saved folder for each feed will have its own Diode connector. This is for two reasons:

1. I am able to see the creator of the feed and know where the data comes from as the author is sometimes wrong or blank.
2. To control the data ingest flow if needed or refeed data etc etc

**Question 1**: As per the attached photo, I am wondering why the creator is admin when I have set my user token on the diode and also attempted to map the DIODE_IMPORT_APPLICANT_MAPPINGS. Ultimately, setting the user OPENCTI_TOKEN=${OPENCTI_MITRE_USER_TOKEN} should ingest it as that user, shouldn't it?
![Screenshot 2024-05-28 080500](https://github.com/OpenCTI-Platform/connectors/assets/129349395/d710bc8f-5cb0-4d5d-9126-d1636870264e)

```
  connector-diode-import-mitre:
    image: opencti/connector-diode-import:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=${OPENCTI_MITRE_USER_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_ID}
      - CONNECTOR_NAME=Diode Import
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - DIODE_IMPORT_APPLICANT_MAPPINGS=dce04c52-f925-437c-b1c1-cdb992441c61:a1d6c793-4ed6-420e-a368-00011580561d
      - DIODE_IMPORT_GET_FROM_DIRECTORY_PATH=/data
      - DIODE_IMPORT_GET_FROM_DIRECTORY_RETENTION=7
    restart: always
    volumes:
      - type: bind
        source: "/mnt/connector/8.Test-Backup/c.mitre_IN"
        target: /data
```
**Question 2:** Does the diode connector support the ability to CONNECTOR_UPDATE_EXISTING_DATA?

Environment
OS - Ubuntu 22 and Red Hat 8.9
OpenCTI version: 6.1.4
OpenCTI client: frontend
Other environment details: N/A
Reproducible Steps
N/A
