### ISSUE TITLE
UrlScan Enrichment Connector constant restart

### ISSUE THREAD

**Issue by demonoidvk** [OpenCTI-Platform/connectors#2194]
## Prerequisites

- [x ] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview/) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting/) page and didn't find anything relevant to my problem.
- [ x] I went through old GitHub issues and couldn't find anything relevant
- [ x] I googled the issue and didn't find anything relevant

## Description
The urlscan-enrichment connector running via docker, with v6.1.6, constantly restarts.

p.s I might be making a mistake here, so please let me know.

Logs of the container:
![image](https://github.com/OpenCTI-Platform/connectors/assets/18901770/2dd94628-0a81-4f80-bc59-24c95355b315)

yml for connector:
```yaml
  connector-urlscan-enrichment:
    image: opencti/connector-urlscan-enrichment:6.1.6
    environment:
      # OpenCTI's generic execution parameters:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      # Connector's generic execution parameters:
      - CONNECTOR_ID=cf24a497-bc16-4489-b6d7-8a5208d1fadb
      - CONNECTOR_NAME=Urlscan-enrichment
      - CONNECTOR_SCOPE=url,ipv4-addr,ipv6-addr,domain-name,hostname
      - CONNECTOR_AUTO=false
      - CONNECTOR_LOG_LEVEL=info
      # Connector's custom execution parameters:
      - URLSCAN_ENRICHMENT_API_KEY=<api-key>             # added here, but redacted for sharing on discussion board
      - URLSCAN_ENRICHMENT_API_BASE_URL=https://urlscan.io/api/v1/
      - URLSCAN_ENRICHMENT_IMPORT_SCREENSHOT=true
      - URLSCAN_ENRICHMENT_VISIBILITY=private # Available values : public, unlisted, private
      - URLSCAN_ENRICHMENT_SEARCH_FILTERED_BY_DATE=>now-1y # Available : ">now-1h", ">now-1d", ">now-1y", "[2022 TO 2023]", "[2022/01/01 TO 2023/12/01]"
      - URLSCAN_ENRICHMENT_MAX_TLP=TLP:AMBER # Required, Available values: TLP:CLEAR, TLP:WHITE, TLP:GREEN, TLP:AMBER, TLP:AMBER+STRICT, TLP:RED
    restart: always
    depends_on:
      - opencti
```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 6.1.6
3. OpenCTI client: 
4. Other environment details: NA

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Just start the container.. it constantly goes into restart phase
