### ISSUE TITLE
Issues Integrating OpenCTI with IBM QRadar for Threat Intelligence

### ISSUE THREAD

**Issue by KARINKISH1** [OpenCTI-Platform/connectors#2330]
**Environment**
OS (where OpenCTI server runs): Ubuntu 22.04.2 LTS
OpenCTI version: OpenCTI 6.2.2
OpenCTI client: Docker
Other environment details: IBM QRadar 7.5.0

**Prerequisites**

- [x]  I read the Deployment and Setup section of the OpenCTI documentation as well as the Troubleshooting page and didn't find anything relevant to my problem.
- [x]  I went through old GitHub issues and couldn't find anything relevant.
- [x]  I googled the issue and didn't find anything relevant.

I'm having trouble integrating OpenCTI with IBM QRadar using the OpenCTI QRadar Stream Connector. The goal is for IBM QRadar to utilize data from OpenCTI for checking IPv4, IPv6, domains, hashes, etc. I have followed the provided instructions and added the following Stream Connector in docker-compose.yml:

```
connector-qradar:
    image: opencti/connector-qradar:6.2.2
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=my_connector_id
      - CONNECTOR_LIVE_STREAM_ID=live # ID of the live stream created in the OpenCTI UI
      - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true
      - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true
      - CONNECTOR_NAME=OpenCTI QRADAR Connector
      - CONNECTOR_SCOPE=qradar
      - CONNECTOR_LOG_LEVEL=info
      - QRADAR_URL=my_url
      - QRADAR_URL_REFERENCE=/api/reference_data_collections/sets
      - QRADAR_TOKEN=my_token
      - QRADAR_SSL_VERIFY=false
      - QRADAR_REFERENCE_NAME=opencti
      - QRADAR_IGNORE_TYPES=label,marking-definition,identity
    restart: always
    depends_on:
      - opencti
``` 

**Reproducible Steps**
Steps to create the smallest reproducible scenario:

1. Created an API with administrator rights in IBM Qradar.
2. Added the Stream Connector configuration to docker-compose.yml as shown above.
3. Started the OpenCTI by the next command:
```
docker-compose up -d
```
4. Checked logs  

**Additional information**
I have specific error messages in the logs. Below are the relevant logs:

```
{"timestamp": "2024-07-11T06:24:20.671324Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "[ERROR-API] API request failed during second attempted creation.", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 91, in create\n    r.raise_for_status()\n  File \"/usr/local/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 422 Client Error: 422 for url: https://10.20.100.10/api/reference_data_collections/sets/opencti_StixFile\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 91, in create\n    r.raise_for_status()\n  File \"/usr/local/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 422 Client Error: 422 for url: https://10.20.100.10/api/reference_data_collections/sets?element_type=ALN&name=opencti_StixFile", "attributes": {"entity_id": "file--83e0bef6-3ba6-5065-8ddb-a49acdf1f08d", "entity_type -> type": "file -> StixFile", "status_code": 422, "reason": "422", "error": "{\"http_response\":{\"code\":422,\"message\":\"The request was well-formed but was unable to be followed due to semantic errors\"},\"code\":10,\"description\":\"\",\"details\":{},\"message\":\"Request body must be populated for body parameter \\\"body\\\"\"}"}}
```

Thank you in advance for your assistance!
