### ISSUE TITLE
Unable to receive unit42 TAXII feed

### ISSUE THREAD

**Issue by hiitisui** [OpenCTI-Platform/connectors#2494]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Ubuntu 22.04 LTS
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
OpenCTI 6.2.12
3. OpenCTI client: { e.g. frontend or python }
frontend
4. Other environment details:
Fronend 1 node, Injestion node 4 nodes(4 nodes workers per injestion node)
Search engine: elk - 8.15.0
RabbitMQ: 3.12.14
Redis: 7.4.0

docker-compose.yml
```
  connector-taxii2:
    image: unit42taxii:latest
    environment:
      - OPENCTI_URL=http://actual_opencti_url
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=actual_id
      - CONNECTOR_NAME=Unit 42 Adversary Playbooks TAXII2
      - CONNECTOR_SCOPE=ipv4-addr,ipv6-addr,vulnerability,domain,url,file-sha256,file-md5,file-sha1
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=debug
      - TAXII2_DISCOVERY_URL=https://stix2.unit42.org/taxii/ # Required
      - TAXII2_USERNAME=actual_username # Required
      - TAXII2_PASSWORD=actual_password
      - TAXII2_USE_TOKEN=false
      - TAXII2_V21=false # Is TAXII v2.1
      - TAXII2_COLLECTIONS=actual_collections
      - TAXII2_INITIAL_HISTORY=24 # Required, in hours
      - TAXII2_INTERVAL=1 # Required, in hours
      - TAXII2_VERIFY_SSL=false
      - TAXII2_CREATE_INDICATORS=true # Generate indicators for ingested observables
      - TAXII2_CREATE_OBSERVABLES=true # Generate observables for ingested indicators
      - TAXII2_ADD_CUSTOM_LABEL=true # Enable custom label
      - TAXII2_CUSTOM_LABEL= # Custom label added to all objects
      - TAXII2_FORCE_PATTERN_AS_NAME=false
      - "TAXII2_FORCE_MULTIPLE_PATTERN_NAME=Multiple Indicators"
```

# Reproducible Steps

Steps to create the smallest reproducible scenario:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. **Environment Setup**:
   - A free account was created at the following URL to obtain the TAXII feed:
     https://stix2.unit42.org/
   - From the dashboard of this site, the TAXII URL and collection IDs were obtained. There are two types of collection IDs: reports and playbooks. The feed is retrieved using BASIC authentication with a user ID and password. It was confirmed that this specification works correctly by retrieving the feed with the following TAXII client in Python:
     https://github.com/oasis-open/cti-taxii-client

   - A `docker-compose.yml` file was used to set up the OpenCTI platform, RabbitMQ, TAXII2 Connector, and Worker.
   - The TAXII2 Connector configuration included the Unit42 TAXII2 server URL, authentication credentials (replaced with 'actual_username' and 'actual_password'), and collection IDs. Below is an excerpt of the configuration.

   ```yaml
   environment:
      - OPENCTI_URL=http://192.168.125.111:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=49643216-6f8b-48be-8560-009b10f86896
      - CONNECTOR_NAME=Unit 42 Adversary Playbooks TAXII2
      - TAXII2_DISCOVERY_URL=https://stix2.unit42.org/taxii/
      - TAXII2_USERNAME=actual_username
      - TAXII2_PASSWORD=actual_password
      - TAXII2_COLLECTIONS=playbooks.5ac266d8-de48-3d6b-83f1-c4e4047d6e44,reports.ca8bf6bb-4063-3588-887d-1c3e16c634d8
      - TAXII2_VERIFY_SSL=false
   ```

2. **Running the TAXII2 Connector**:
   - The TAXII2 Connector was started and attempted to connect to the Unit42 TAXII server.
   - The Connector began the process of retrieving STIX 2 objects from the specified API root and collection.

3. **Comma-Separated Processing Verification**:
   - The `TAXII2_COLLECTIONS` setting in the TAXII2 Connector was tested with the following two values:
     - `TAXII2_COLLECTIONS=5ac266d8-de48-3d6b-83f1-c4e4047d6e44`
     - `TAXII2_COLLECTIONS=playbooks.5ac266d8-de48-3d6b-83f1-c4e4047d6e44,reports.ca8bf6bb-4063-3588-887d-1c3e16c634d8`
   - This tested whether the Connector could correctly recognize the collection IDs and retrieve STIX objects.

4. **Review of Error Logs**:
   - Upon reviewing the Connector's logs, the following error message was observed:
```
   {"timestamp": "2024-08-17T07:15:40.308721Z", "level": "ERROR", "name": "Unit 42 Adversary Playbooks TAXII2", "message": "Collection ca8bf6bb-4063-3588-887d-1c3e16c634d8 does not exist in API root Indicators from directory 'reports'", "exc_info": "Traceback (most recent call last):
  File "/opt/opencti-taxii2/taxii2.py", line 217, in run
    coll = self._get_collection(root, coll_title)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-taxii2/taxii2.py", line 461, in _get_collection
    raise TAXIIServiceException(msg)
taxii2client.exceptions.TAXIIServiceException: Collection ca8bf6bb-4063-3588-887d-1c3e16c634d8 does not exist in API root Indicators from directory 'reports'"}

```
## Expected Output

- The TAXII2 Connector successfully connects to the Unit42 TAXII2 server, retrieves STIX 2 objects from the specified API root and collection, and sends them to the OpenCTI platform.
- All data is successfully imported and stored in the OpenCTI database.

## Actual Output

- The TAXII2 Connector attempted to connect to the Unit42 TAXII2 server and retrieve STIX 2 objects from the specified API root and collection.
- However, an issue with processing the API roots within the script led to the correct API root not being found, preventing the proper retrieval and processing of STIX objects.

### API Root Issue

- In the `taxii2.py` script, there was an issue with the API root retrieval process.
- As shown in the logs below, the Connector sometimes failed to find the specified API root correctly.

  ```plaintext
  {"timestamp": "2024-08-17T07:14:26.210216Z", "level": "ERROR", "name": "Unit 42 Adversary Playbooks TAXII2", "message": "Api Root Indicators from directory ''reports'' does not exist in the TAXII server"}
  ```

- Specifically, the logic in the script that determines whether a specific string is included at the end of the API root URL was insufficient, causing the correct API root to sometimes not be found.

### Comma-Separated Processing Error

- The collection information was processed as comma-separated values, but this processing did not match the structure of the Unit42 feed.
- The `TAXII2_COLLECTIONS` environment variable was specified with multiple collection IDs separated by commas as shown below:

  ```plaintext
  TAXII2_COLLECTIONS=playbooks.5ac266d8-de48-3d6b-83f1-c4e4047d6e44,reports.ca8bf6bb-4063-3588-887d-1c3e16c634d8
  ```

- However, the script's processing of this comma-separated information was incorrect, and it failed to correctly obtain the collection IDs. As a result, the following error logs were observed:

  ```plaintext
  {"timestamp": "2024-08-17T07:15:40.308721Z", "level": "ERROR", "name": "Unit 42 Adversary Playbooks TAXII2", "message": "Collection ca8bf6bb-4063-3588-887d-1c3e16c634d8 does not exist in API root Indicators from directory 'reports'"}
  ```

- This caused the script to reference incorrect API roots or collection IDs, leading to the failure to retrieve STIX objects.

**Comment by annoyingapt** [comment]
Did you try the opencti taxii image? I'm not sure who manages the one you have in you config.

**Comment by annoyingapt** [comment]
OK, so the problem you are having is you are putting the collection id where the collection title should go. Confusingly, Unit42 doesn't put the collection title in the Taxii Feed Portal, so the only way you would be able to find it is if you use a tool like Postman to follow api_roots and see what the title is. However, I would just recommend using wildcards to save you from having to do this. Hopefully this puts you on the right path.

Choose one of the following collections to resolve the issue.
```
- "TAXII2_COLLECTIONS=playbooks.Indicators from directory 'playbooks',reports.Indicators from directory 'reports'"
- "TAXII2_COLLECTIONS=playbooks.*,reports.*"
- "TAXII2_COLLECTIONS=*.*"
```

My config
```
connector-unit42:
    image: opencti/connector-taxii2:6.2.13
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=0f43712f-02d8-4484-8705-481dcb75700c
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Unit42
      - CONNECTOR_SCOPE=ipv4-addr,ipv6-addr,vulnerability,domain,url,file-sha256,file-md5,file-sha1
      - CONNECTOR_CONFIDENCE_LEVEL=80
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=error
      - TAXII2_DISCOVERY_URL=${CONNECTOR_UNIT42_TAXII_URL}
      - TAXII2_USERNAME=${CONNECTOR_UNIT42_TAXII_USERNAME}
      - TAXII2_PASSWORD=${CONNECTOR_UNIT42_TAXII_PASSWORD}
      - TAXII2_V21=false
      - "TAXII2_COLLECTIONS=playbooks.Indicators from directory 'playbooks',reports.Indicators from directory 'reports'"
      - TAXII2_INITIAL_HISTORY=99999
      - TAXII2_INTERVAL=1
      - TAXII2_VERIFY_SSL=true
      - TAXII2_CREATE_INDICATORS=true
      - TAXII2_CREATE_OBSERVABLES=true
      - TAXII2_ADD_CUSTOM_LABEL=true
      - TAXII2_CUSTOM_LABEL=unit42
      - TAXII2_FORCE_PATTERN_AS_NAME=true
      - "TAXII2_FORCE_MULTIPLE_PATTERN_NAME=Multiple Indicators"
      - TAXII2_USE_APIKEY=false
      - TAXII2_USE_TOKEN=false
```

Screenshots
![image](https://github.com/user-attachments/assets/6617231b-767c-4f8e-b381-c16bf23c8320)
![image](https://github.com/user-attachments/assets/a1b5d40a-d265-401c-88c6-6c8bc002e100)

Note:
There are errors for Element(s) not found, but I think this is because my initial history is not going far enough back or something, I can't remember what these errors are about.

**Comment by annoyingapt** [comment]
For the author, the way you do it is create a new user with connector permissions. Then use their api key instead of the admin in your config. Regarding the TLP, it is up to the feed source to determine the TLP, so you would need to edit the object before it was being ingested and add the marking yourself. Alternatively, you can configure a minimum TLP in Opencti, so Opencti will set it with that, if none is provided. Lastly, there is probably a way to use automation to do it, but I don't use that.

**Comment by Jipegien** [comment]
@annoyingapt Thanks for your help on the matter!
@hiitisui I am closing the issue as the "bug" seems to be solved. Do not hesitate to reopen it if it is not the case. If you think improvements should be done on the connector, feel free to open an feature request issue :)

**Comment by Jonesckevin** [comment]
**From the data above, This one worked for me. I did get some errors but some data did get associated.**

````yaml
  connector-taxii2:
    image: opencti/connector-taxii2:$VERSION
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=$OPENCTI_ADMIN_TOKEN
      - CONNECTOR_ID=$CONNECTOR_TAXII2_ID
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Unit42-PaltoAlto
      - CONNECTOR_SCOPE=ipv4-addr,ipv6-addr,vulnerability,domain,url,file-sha256,file-md5,file-sha1
      - CONNECTOR_CONFIDENCE_LEVEL=80
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=error
      - TAXII2_DISCOVERY_URL=$CONNECTOR_UNIT42_TAXII_URL
      - TAXII2_USERNAME=$CONNECTOR_UNIT42_TAXII_USERNAME
      - TAXII2_PASSWORD=$CONNECTOR_UNIT42_TAXII_PASSWORD
      - TAXII2_V21=false
      - "TAXII2_COLLECTIONS=playbooks.Indicators from directory 'playbooks',reports.Indicators from directory 'reports'"
      - TAXII2_INITIAL_HISTORY=99999
      - TAXII2_INTERVAL=1
      - TAXII2_VERIFY_SSL=true
      - TAXII2_CREATE_INDICATORS=true
      - TAXII2_CREATE_OBSERVABLES=true
      - TAXII2_ADD_CUSTOM_LABEL=true
      - TAXII2_CUSTOM_LABEL=unit42
      - TAXII2_FORCE_PATTERN_AS_NAME=true
      - "TAXII2_FORCE_MULTIPLE_PATTERN_NAME=Multiple Indicators"
      - TAXII2_USE_APIKEY=false
      - TAXII2_USE_TOKEN=false
    restart: always
````
```yaml
CONNECTOR_UNIT42_TAXII_USERNAME=ChangeMe
CONNECTOR_UNIT42_TAXII_PASSWORD=ChangeMe
CONNECTOR_UNIT42_TAXII_URL=https://stix2.unit42.org/taxii/
CONNECTOR_UNIT42_ID=a0f620fb-1494-116f-8ebc-a28f3207d986
```
- It gave me a total of 343 Entities/Relations.
 ![image](https://github.com/user-attachments/assets/3f53a559-f420-4b15-ad6b-7e32be726e24)

**As Seen Here**
![image](https://github.com/user-attachments/assets/18e581ae-0756-4081-9df2-546315bfdadc)


![image](https://github.com/user-attachments/assets/107dde6c-d5a1-42ad-91d8-ad493c22d017)
> Errors: `{'name': 'MISSING_REFERENCE_ERROR', 'error_message': 'Element(s) not found'}`
