### ISSUE TITLE
MISP connector importing everything EXCEPT indicators & observables

### ISSUE THREAD

**Issue by ckane** [OpenCTI-Platform/connectors#308]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

MISP connector won't import observables/indicators, will import everything else. I am trying to compare both systems, and MISP has a bunch of existing feed data out there that is available to import into a newly-configured instance. I figured that pulling this data into MISP, and then further pulling it into OpenCTI, would give me a good comparative scenario for evaluating the two applications - as the underlying data would be the same, and also has a lot of semi-overlapping events/reports.

## Environment

1. OS (where OpenCTI server runs): Using https://github.com/OpenCTI-Platform/docker to deploy on Docker on Ubuntu 18.04 LTS
2. OpenCTI version: 4.3.4
3. OpenCTI client: 4.3.4
4. MISP version 2.4.140

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. MISP is installed, API key is correct (verified because some data is being imported)
2. Enabled all feeds in MISP (under Sync Actions -> List Feeds, "Load default feed metadata" and then enabled all of them)
3. Fetch and store all feed data
4. Wait / verify that feed import into MISP completed
5. Added "misp" connector to `docker-compose.yml` from OpenCTI-Platform/docker repo

## Expected Output

All Events, Indicators, Observations, Threat actors, Intrusion sets, Malwares and Attack Patterns are imported from the MISP instance, with the proper entity relationships forged between them (where compatible with the schema & data model).

## Actual Output

The Events, Threat Actors, Intrusion Sets, Malware, and Attack Patterns are imported, but the Indicators & Observables seem to be ignored.
 
## Additional information

MISP service connector added to `docker-compose.yml`:
```yaml
  connector-misp-ckane-threat-int:
    image: opencti/connector-misp:4.3.4
    depends_on:
      - opencti
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MISP_MY_INSTANCE_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=my-misp-instance
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=2
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_UPDATE_EXISTING_DATA=True
      - MISP_URL=http://my.misp.server/
      - MISP_REFERENCE_URL=http://my.misp.server/
      - MISP_KEY=${MY_MISP_AUTOMATION_KEY}
      - MISP_SSL_VERIFY=False
      - MISP_DATETIME_ATTRIBUTE=timestamp
      - MISP_CREATE_REPORTS=True
      - MISP_INTERVAL=5
```

I have tested with/without `MISP_IMPORT_ONLY_PUBLISHED=True` as well as using `MISP_IMPORT_CREATOR_ORGS` to limit what is imported, but I get the same behavior no matter what.
