### ISSUE TITLE
[VirusTotal] invalid literal for int() with base 10: '10 creation'

### ISSUE THREAD

**Issue by dominictory** [OpenCTI-Platform/connectors#3174]
## Description

When trying to enrich an observable with VirusTotal, the connector shows `Waiting` whilst the container logs show errors:

`invalid literal for int() with base 10: '10 creation'`

## Environment

6.4.2

## Reproducible Steps

Enrich observable using VirusTotal connector
Observe error logs

## Expected Output

IPv4 observable is sent for enrichment and results are returned

## Actual Output

Errors

**Comment by dominictory** [comment]
> Hello [@dominictory](https://github.com/dominictory) . Do you have any information that would allow us to reproduce the error ?

Hi, I simply tried to enrich an observable with VirusTotal. It showed 'waiting' in the UI but showed errors in the container logs as above.

**Comment by romain-filigran** [comment]
Can you share the complete stacktrace ?

**Comment by romain-filigran** [comment]
Can you share the connector configuration ? We believe there is a string “creation” interpreted as a configuration value

**Comment by dominictory** [comment]
> Can you share the complete stacktrace ?

Sorry for this did you want me to set connector to debug and run enrichment again?

> Can you share the connector configuration ? We believe there is a string “creation” interpreted as a configuration value

```
connector-virustotal:
    image: opencti/connector-virustotal:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=http://opencti-connector:8080
      - OPENCTI_TOKEN=2eec34c8-681f-49d6-8628-95e3fe12d139
      - CONNECTOR_ID=a5f0f21d-4088-485d-b2b0-91fc2d7e6183
      - CONNECTOR_NAME=VirusTotal
      - CONNECTOR_SCOPE=StixFile,Artifact,IPv4-Addr,Domain-Name,Url,Hostname
      - CONNECTOR_AUTO=false
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_EXPOSE_METRICS=false
      - VIRUSTOTAL_TOKEN=redacted
      - VIRUSTOTAL_MAX_TLP=TLP:AMBER
      - VIRUSTOTAL_REPLACE_WITH_LOWER_SCORE=true
      - VIRUSTOTAL_FILE_CREATE_NOTE_FULL_REPORT=true
      - VIRUSTOTAL_FILE_UPLOAD_UNSEEN_ARTIFACTS=true
      - VIRUSTOTAL_FILE_INDICATOR_CREATE_POSITIVES=10 creation
      - VIRUSTOTAL_FILE_INDICATOR_VALID_MINUTES=2880
      - VIRUSTOTAL_FILE_INDICATOR_DETECT=true
      - VIRUSTOTAL_IP_INDICATOR_CREATE_POSITIVES=10
      - VIRUSTOTAL_IP_INDICATOR_VALID_MINUTES=2880
      - VIRUSTOTAL_IP_INDICATOR_DETECT=true
      - VIRUSTOTAL_IP_ADD_RELATIONSHIPS=true
      - VIRUSTOTAL_DOMAIN_INDICATOR_CREATE_POSITIVES=10
      - VIRUSTOTAL_DOMAIN_INDICATOR_VALID_MINUTES=2880
      - VIRUSTOTAL_DOMAIN_INDICATOR_DETECT=true
      - VIRUSTOTAL_DOMAIN_ADD_RELATIONSHIPS=true
      - VIRUSTOTAL_URL_UPLOAD_UNSEEN=true
      - VIRUSTOTAL_URL_INDICATOR_CREATE_POSITIVES=10
      - VIRUSTOTAL_URL_INDICATOR_VALID_MINUTES=2880
      - VIRUSTOTAL_URL_INDICATOR_DETECT=true
    restart: always
```
