### ISSUE TITLE
[CrowdStrike] 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by dominictory** [OpenCTI-Platform/connectors#3275]
## Description

We are seeing the below error constantly (4-5 messages per minute) with CrowdStrike:

```
'NoneType' object cannot be interpreted as an integer
```

It appears no work is being done with this connector whilst seeing these messages as it shows INACTIVE. Connector was working a few days ago (10/1/25) and no modifications have been made since.

## Environment

6.4.6

## Reproducible Steps

```
connector-crowdstrike:
    image: opencti/connector-crowdstrike:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=http://opencti-connector:8080
      - OPENCTI_TOKEN=247e6c24-970e-4f20-89ab-3d3c780969bf
      - CONNECTOR_ID=5f00b533-db94-4326-a5c7-d915257d5f83
      - CONNECTOR_NAME=CrowdStrike
      - CONNECTOR_SCOPE=crowdstrike
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_DURATION_PERIOD=PT30M
      - CROWDSTRIKE_BASE_URL=https://api.eu-1.crowdstrike.com
      - CROWDSTRIKE_CLIENT_ID=redacted
      - CROWDSTRIKE_CLIENT_SECRET=redacted
      - CROWDSTRIKE_TLP=AMBER
      - CROWDSTRIKE_CREATE_OBSERVABLES=true
      - CROWDSTRIKE_CREATE_INDICATORS=true
      - CROWDSTRIKE_SCOPES=actor
      - CROWDSTRIKE_ACTOR_START_TIMESTAMP=0
      - CROWDSTRIKE_REPORT_START_TIMESTAMP=0
      - CROWDSTRIKE_REPORT_STATUS=New
      - CROWDSTRIKE_REPORT_INCLUDE_TYPES=notice,tipper,intelligence report,periodic report
      - CROWDSTRIKE_REPORT_TYPE=threat-report
      - CROWDSTRIKE_REPORT_GUESS_MALWARE=true
    restart: always
```

## Expected Output

Connector ingests CrowdStrike data.

## Actual Output

Nothing except error message.
