### ISSUE TITLE
Exporting Data - CSV Not Available

### ISSUE THREAD

**Issue by PandaLyfe** [OpenCTI-Platform/connectors#331]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

When trying to export data, only the JSON option is available. I restarted OpenCTI and the connector is found within the docker-compose.yml file. I also checked the configurations. When reviewing the logs, I see this:

```
ERROR:root:Cant create key for Connector from empty data
{'name': 'UnsupportedError', 'message': 'Cant create key for Connector from empty data'}
INFO:root:Listing Threat-Actors with filters null.

```

## Environment

1. OS Linux 20.10
2. OpenCTI version: 4.4.0
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click "export"
2. Select format
3. JSON is the only format available

## Expected Output

When attempting to export data from OpenCTI, we would like to have the CSV format available. 

## Actual Output

When trying to export data, only JSON option is available. 
 
## Additional information

None.

**Comment by SamuelHassine** [comment]
Hello @PandaLyfe,

Please can you copy paste your ExportCSV connector configuration?

Kind regards,
Samuel

**Comment by PandaLyfe** [comment]
Hey @SamuelHassine 

Here is what I have configured for the CSV export connector:

```
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:4.4.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
```
OPENCTI_ADMIN_TOKEN = UUID
CONNECTOR_EXPORT_FILE_CSV_ID = UUID

And the connector can be found here at: https://github.com/OpenCTI-Platform/connectors/tree/master/export-file-csv

Please let me know if you need any further information. 

Kind regards, 
Jen
