### ISSUE TITLE
Deployment of lightweight connectors independent of the Platform

### ISSUE THREAD

**Issue by lydiym** [OpenCTI-Platform/connectors#3432]
## Use case

**Deployment of lightweight connectors independent of the Platform**

Currently, in case of connectors deployment it's necessary to provide Platform with requirements (Elasticsearch, RabbitMQ, etc...). 
In case of use `CONNECTOR_SEND_TO_DIRECTORY: true` and `CONNECTOR_SEND_TO_QUEUE: false` according [feature](https://github.com/OpenCTI-Platform/client-python/issues/603), with [connector-diode-import](https://github.com/OpenCTI-Platform/connectors/tree/11a05bffeda5111577b326fbd7db4a71842af99a/external-import/diode-import), the Platform with requirements isn't useful, but it still mandatory to provide it, because it' necessary for `connector_helper` and connector states storing. It's quite expensive in terms of resources, and unnecessarily complicates the deployment and configuration of such connectors.

It very useful and flexible to allow store connectors state in local files (for example `json`)!

## Current Workaround

There is no workaround. It's necessary to provide Platform with requirements (Elasticsearch, RabbitMQ, etc...). 

## Proposed Solution

Add options for connectors and [connector_helper](https://github.com/OpenCTI-Platform/client-python/blob/0de9da36b8fdaf6a0390033d04662f7e82a9a11d/pycti/connector/opencti_connector_helper.py#L754):

```yml
connector:
	state_storage_platform: true by default
	state_storage_directory: false by default
	state_storage_directory_path: None by default (will represent the path of connector state file storing)
```

# Format
standard connector state format

# How to test
Configured any connectors using the new options and check the directory content.
