### ISSUE TITLE
CrowdStrike connector's message size incompatible with RabbitMQ 4.0

### ISSUE THREAD

**Issue by initstring** [OpenCTI-Platform/connectors#3528]
## Description

RabbitMQ 4.0 introduced a new default to [limit message sized to 16MB](https://github.com/rabbitmq/rabbitmq-server/pull/11455). This ends up breaking the CrowdStrike connector, causing it to fail during run with messages like this:

```
{"timestamp": "2025-03-01T00:23:41.164115Z", "level": "ERROR", "name": "Crowdstrike", "message": "CrowdStrike connector internal error: (406, 'PRECONDITION_FAILED - message size 47984031 is larger than configured max size 16777216')"

(snipped rest of error)
```

RabbitMQ 4.0 is the official version listed in the OpenCTI docker-compose file [here](https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml#L56), so it is likely others will run into this.

This can actually be solved easily by passing the following env var to the RabbitMQ container, and then the data ingestion will proceed without issue.

```
RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit max_message_size 100000000
```

 I'm happy to open a PR somewhere but am not sure where it should go - possibly in the CrowdStrike connector docs, as not all users may want to change this value?

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }: Kubernetes
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }: 6.5.3
3. OpenCTI client: { e.g. frontend or python }: N/A
4. Other environment details: CrowdStrike connector v6.5.3, RabbitMQ 4.0-management

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Install current recommended versions of OpenCTI and CrowdStrike connector
2. Try to sync CrowdStrike including default recommended report types
3. View logs, observe failue

## Expected Output

Expect connector to complete without failure.

**Comment by initstring** [comment]
Created documentation PR here: https://github.com/OpenCTI-Platform/connectors/pull/3537

**Comment by dominictory** [comment]
Hi, I  added `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit max_message_size 100000000"` to my docker-compose as I want to fix the issue, however my stack now won't start as it says the RabbitMQ container is unhealthy:
```
rabbitmq:
    image: rabbitmq:${RMQ_VERSION}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit max_message_size 100000000"
    volumes:
      - amqpdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
```
