### ISSUE TITLE
[Elastic Connector] Error when working with Elastic Platfrom 8

### ISSUE THREAD

**Issue by Nyarlad** [OpenCTI-Platform/connectors#3850]
## Description
When initializing, the connector cannot create the necessary alias in ELK. It seems to me that the problem is in the incompatibility of the index template in the connector with ELK version 8.

## Environment
1. OpenCTI version: 6.4.11
2. Elastic Platform version: 8.13.3
3. ILM in elastic: enabled

## Reproducible Steps
Last connector configuration:
```
connector-elastic:
  image: opencti/connector-elastic:6.4.11
  environment:
    - OPENCTI_URL=...
    - OPENCTI_TOKEN=...
    - CONNECTOR_ID=...
    - CONNECTOR_LIVE_STREAM_ID=...
    - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true
    - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true
    - "CONNECTOR_NAME=OpenCTI Elastic Connector"
    - CONNECTOR_SCOPE=elastic
    - CONNECTOR_CONFIDENCE_LEVEL=80
    - CONNECTOR_LOG_LEVEL=debug
    - "CONNECTOR_ENTITY_NAME=Elastic Detection Cluster"
    - "CONNECTOR_ENTITY_DESCRIPTION=Elasticsearch detection engine cluster"
    - CONNECTOR_MODE=ecs
    - ELASTICSEARCH_APIKEY=...
    - ELASTICSEARCH_HOSTS=...
    - CONNECTOR_JSON_CONFIG={"output":{"include_labels":false},"setup":{"ilm":{"enabled":true,"policy_name":"opencti","pattern":"000001","overwrite":true},"template":{"enabled":true,"name":"opencti","pattern":"opencti-*","overwrite":true}}}
```

## Additional information
At first I didn't configure the setup.ilm.pattern parameter and got this error:
```
{"timestamp": "2025-04-22T09:36:52.327805Z", "level": "INFO", "name": "elastic", "message": "Creating alias 'opencti' to pattern '<opencti-{now/d}-000001>'", "taskName": null}
{"timestamp": "2025-04-22T09:36:52.335248Z", "level": "WARNING", "name": "elasticsearch", "message": "POST https://elastic:9107/%3Copencti-%7Bnow%2Fd%7D-000001%3E/_doc [status:400 request:0.007s]", "taskName": null}
{"timestamp": "2025-04-22T09:36:52.335388Z", "level": "DEBUG", "name": "elasticsearch", "message": "> \n                {\n                    \"aliases\": {\n                        \"opencti\": { \"is_write_index\": true }\n                    }\n                }\n                ", "taskName": null}
{"timestamp": "2025-04-22T09:36:52.335473Z", "level": "DEBUG", "name": "elasticsearch", "message": "< {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"data_stream [<opencti-{now/d}-000001>] must not contain the following characters ['<','*','?','>','|',',','/','\\\\',' ','\\\"']\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"data_stream [<opencti-{now/d}-000001>] must not contain the following characters ['<','*','?','>','|',',','/','\\\\',' ','\\\"']\"},\"status\":400}", "taskName": null}
```

Then I decided to replace pattern and remove datemath from there, but this error appeared:
```
{"timestamp": "2025-04-22T09:26:25.663655Z", "level": "INFO", "name": "elastic", "message": "Creating alias 'opencti' to pattern 'opencti-000001'", "taskName": null}
{"timestamp": "2025-04-22T09:26:25.689619Z", "level": "WARNING", "name": "elasticsearch", "message": "POST https://elastic:9107/opencti-000001/_doc [status:500 request:0.026s]", "taskName": null}
{"timestamp": "2025-04-22T09:26:25.689815Z", "level": "DEBUG", "name": "elasticsearch", "message": "> \n                {\n                    \"aliases\": {\n                        \"opencti\": { \"is_write_index\": true }\n                    }\n                }\n                ", "taskName": null}
{"timestamp": "2025-04-22T09:26:25.689922Z", "level": "DEBUG", "name": "elasticsearch", "message": "< {\"error\":{\"root_cause\":[{\"type\":\"illegal_state_exception\",\"reason\":\"[_data_stream_timestamp] meta field has been disabled\"}],\"type\":\"illegal_state_exception\",\"reason\":\"[_data_stream_timestamp] meta field has been disabled\"},\"status\":500}", "taskName": null}
```
