### ISSUE TITLE
ExportFileCsv Connector Fails on CSV Export — NoneType Found

### ISSUE THREAD

**Issue by avinashKumarYadav** [OpenCTI-Platform/connectors#3899]
**Description**:  
`ExportFileCsv` connector crashes with `TypeError: expected str instance, NoneType found` during indicator export

---

### 🧩 Affected Component

- **Connector**: `ExportFileCsv`
- **Docker Image**: `opencti/connector-export-file-csv:6.5.9`
- **OpenCTI Version**: [6.5.9]
- **Connector Type**: `INTERNAL_EXPORT_FILE`

---

### ⚙️ Connector Configuration

```yaml
image: opencti/connector-export-file-csv:6.5.9
environment:
  - OPENCTI_URL=http://opencti:8080
  - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
  - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID}
  - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
  - CONNECTOR_NAME=ExportFileCsv
  - CONNECTOR_SCOPE=text/csv
  - CONNECTOR_LOG_LEVEL=info
```

---

### 🔁 Steps to Reproduce

1. Go to `Observations > Indicators`.
2. Filter using a label (e.g., `Label = actor/famouscholima`).
3. Select ~365 indicators.
4. Click **Export**.
5. Set:
   - **Export format**: `text/csv`
   - **Export type**: `Simple export (just the entity)`
   - **Content marking**: `TLP:RED`
   - **File marking**: `TLP:RED`
6. Click **Create**.

---

### ❌ Actual Behavior

The export fails and displays this error in the UI:
```
Connector ready to process the operation, sequence item 0: expected str instance, NoneType found
```

---

### 🪵 Connector Logs

```{"timestamp": "2025-04-29T12:32:04.404127Z", "level": "ERROR", "name": "ExportFileCsv", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.12                /site-packages/pycti/connector/opencti_connector_helper.py\", line 404, in _data_handler\n    message = self.callback(event_data)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-export-file-csv/export-file-csv.p                y\", line 288, in _process_message\n    self._export_list(data, entities_list, list_filters)\n  File \"/opt/opencti-connector-export-file-csv/export-file-csv.py\", line 105, in _export_list\n    csv_data = self.export_dict_list_to_csv(en                tities_list)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-export-file-csv/export-file-csv.py\", line 75, in export_dict_list_to_csv\n    row.append(\",\".join(rrow))\n               ^^^^^^^                ^^^^^^^\nTypeError: sequence item 0: expected str instance, NoneType found", "taskName": null}```

```plaintext
File "/opt/opencti-connector-export-file-csv/export-file-csv.py", line 75, in export_dict_list_to_csv
  row.append(",".join(rrow))
TypeError: sequence item 0: expected str instance, NoneType found
```

---

### 📌 Root Cause

One or more fields in the indicator (e.g., `name`, `pattern`, `description`, etc.) are `null` (`NoneType`), and the connector doesn’t sanitize those before applying `",".join(...)`.

---

### ✅ Expected Behavior

- The connector should gracefully handle missing/null fields.

---

### 🧪 Troubleshooting Performed

- Exporting smaller subsets confirms its working.

---

### 🙏 Request

Please implement a fix in the connector.

---
