### ISSUE TITLE
[URLScan-enrichment] Failures reported for a successful scan.

### ISSUE THREAD

**Issue by rglowe** [OpenCTI-Platform/connectors#4111]
When using the [URLscan-enrichment](https://github.com/OpenCTI-Platform/connectors/tree/master/internal-enrichment/urlscan-enrichment) connector, there are failures reported even though the scan is successful. This seems to occur more reliably if the target URL is a direct file reference, rather than a complete webpage.

The following configuration is being used: 

```
  connector-urlscan-enrichment:
    image: opencti/connector-urlscan-enrichment:6.6.14
    environment:
      # OpenCTI's generic execution parameters:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      # Connector's generic execution parameters:
      - CONNECTOR_ID=<REMOVED>
      - CONNECTOR_NAME=Urlscan
      - CONNECTOR_SCOPE=url,ipv4-addr,ipv6-addr
      - CONNECTOR_AUTO=false
      - CONNECTOR_LOG_LEVEL=info
      # Connector's custom execution parameters:
      - URLSCAN_ENRICHMENT_API_KEY=<REMOVED>
      - URLSCAN_ENRICHMENT_API_BASE_URL=https://urlscan.io/api/v1/
      - URLSCAN_ENRICHMENT_IMPORT_SCREENSHOT=true
      - URLSCAN_ENRICHMENT_VISIBILITY=public # Available values : public, unlisted, private
      - URLSCAN_ENRICHMENT_SEARCH_FILTERED_BY_DATE=>now-1y # Available : ">now-1h", ">now-1d", ">now-1y", "[2022 TO 2023]", "[2022/01/01 TO 2023/12/01]"
      - URLSCAN_ENRICHMENT_MAX_TLP=TLP:AMBER # Required, Available values: TLP:CLEAR, TLP:WHITE, TLP:GREEN, TLP:AMBER, TLP:AMBER+STRICT, TLP:RED
      - URLSCAN_ENRICHMENT_CREATE_INDICATOR=true
    restart: always

```

Testing this using the following observable: `http://37.80.53.179/sshd`  results in an error: `[API-RESULT] The request has been submitted to URLScan, but the URL does not return any data.`

Here are the logs: 

```
{"timestamp": "2025-06-06T01:36:44.425444Z", "level": "INFO", "name": "Urlscan", "message": "Message ack", "attributes": {"tag": 3}}
{"timestamp": "2025-06-06T01:36:44.425800Z", "level": "INFO", "name": "api", "message": "Reading StixCyberObservable", "attributes": {"id": "url--2179f06e-47ae-5535-b2cc-a91fa513468b"}}
{"timestamp": "2025-06-06T01:36:44.446073Z", "level": "INFO", "name": "api", "message": "Listing stix_nested_ref_relationships", "attributes": {"relationship_type": null, "from_id": "e465c878-c5c3-454a-842c-70bdb899de8d", "to_id": null}}
{"timestamp": "2025-06-06T01:36:44.452869Z", "level": "INFO", "name": "api", "message": "Reporting work update_received", "attributes": {"work_id": "work_22d49e42-1468-4b72-b2e7-8fd9bfc8fe22_2025-06-06T01:36:44.329Z"}}
{"timestamp": "2025-06-06T01:36:45.458086Z", "level": "INFO", "name": "Urlscan", "message": "[API-RATE-LIMITS] The URLScan rate limits :", "attributes": {"visibility": "public", "rate_limits": {"day": {"limit": 5000, "percent": 0, "remaining": 4998, "used": 2, "reset": "2025-06-07T00:00:00.000Z"}, "hour": {"limit": 500, "percent": 0, "remaining": 498, "used": 2, "reset": "2025-06-06T02:00:00.000Z"}, "minute": {"limit": 60, "percent": 0, "remaining": 60, "used": 0}}}}
{"timestamp": "2025-06-06T01:36:46.243834Z", "level": "INFO", "name": "Urlscan", "message": "[INFO-SUBMISSION] The urlscan submission request generated the uuid:", "attributes": {"uuid": "019742e2-2413-75de-a5c6-c47cb67e943f", "entity_value": "http://37.80.53.179/sshd"}}
{"timestamp": "2025-06-06T01:37:27.782607Z", "level": "ERROR", "name": "Urlscan", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-urlscan-enrichment/main.py\", line 321, in _process_message\n    json_result = self.client.urlscan_result(uuid)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-urlscan-enrichment/urlscan_enrichment_services/client.py\", line 153, in urlscan_result\n    raise ValueError(\nValueError: [API-RESULT] The request has been submitted to URLScan, but the URL does not return any data.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/pycti/connector/opencti_connector_helper.py\", line 410, in _data_handler\n    message = self.callback(event_data)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-urlscan-enrichment/main.py\", line 357, in _process_message\n    raise ValueError(str(e))\nValueError: [API-RESULT] The request has been submitted to URLScan, but the URL does not return any data."}
{"timestamp": "2025-06-06T01:37:27.782716Z", "level": "INFO", "name": "api", "message": "Reporting work update_processed", "attributes": {"work_id": "work_22d49e42-1468-4b72-b2e7-8fd9bfc8fe22_2025-06-06T01:36:44.329Z"}}
{"timestamp": "2025-06-06T01:37:28.549000Z", "level": "INFO", "name": "Urlscan", "message": "Message processed, thread terminated", "attributes": {"tag": 3}}
```

However, this URL was scanned successfully and a URLscan report is created at: https://urlscan.io/result/019742e2-2413-75de-a5c6-c47cb67e943f
