### ISSUE TITLE
[SOCRadar] Flatten `RADAR_COLLECTION_UUIDS` env vars

### ISSUE THREAD

**Issue by Powlinett** [OpenCTI-Platform/connectors#4194]
## Use case

SOCRadar connector gets feed lists from SOCRadar API. To do so, multiple "collections" IDs can be setup through `RADAR_COLLECTION_UUIDS` config/env var with the following format:

_config.yml_
```yaml
radar_collections_uuid:
  collection_1:
    id: ["COLLECTION_UUID"]
    name: ["COLLECTION_NAME"]
  collection_2:
    id: ["COLLECTION_UUID"]
    name: ["COLLECTION_NAME"]
```

_docker-compose.yml_
```yaml
connector-socradar:
  environment:
    - RADAR_BASE_FEED_URL=ChangeMe
    - RADAR_SOCRADAR_KEY=ChangeMe
    - 'RADAR_COLLECTIONS_UUID={"collection_1":{"id":["COLLECTION_UUID"],"name":["COLLECTION_NAME"]},"collection_2":{"id":["COLLECTION_UUID"],"name":["COLLECTION_NAME"]}}'
```

The format of the config/env var:
1. doesn't really make sense (what is `collection_1`, `collection_2`? why collections' IDs and names are lists?)
2. for env var, is hard to read and write
3. hard to validate at runtime (with pydantic-settings for instance)
4. not needed for the use case, a dict with name/id pairs would be sufficient

## Current Workaround

No current workaround as current codebase expects such data structure.

## Proposed Solution

Deprecate `RADAR_COLLECTION_UUIDS` and introduce `RADAR_FEED_LISTS_IDS`, as flat as possible, i.e.:

_config.yml_
```yaml
feed_lists_ids:
    FEED_LIST_NAME_1: 'ID_1'
    FEED_LIST_NAME_2: 'ID_2'
```

_docker-compose.yml_
```yaml
connector-socradar:
  environment:
    - RADAR_BASE_FEED_URL=ChangeMe
    - RADAR_SOCRADAR_KEY=ChangeMe
    - 'RADAR_FEED_LISTS_IDS={"FEED_LIST_NAME_1": "ID_1", "FEED_LIST_NAME_2": "ID_2"}'
```
