### ISSUE TITLE
[MITRE] Unable to get MITRE connector to work

### ISSUE THREAD

**Issue by 0xd3vnull** [OpenCTI-Platform/connectors#481]
## Description

Attempting to connect MITRE connector to my OpenCTI instance, however I continue to get the error "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."

## Environment

1. OS RHEL 8
2. OpenCTI 5.0.0
3. OpenCTI client: Frontend
4. Other environment details: built using docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Installed OpenCTI connectors  via a git clone.

Modified the docker-compose.yml as follows...

```
version: '3'
services:
  connector-mitre:
    image: opencti/connector-mitre:5.0.0
    environment:
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN={opencti_admin_token}
      - CONNECTOR_ID=6ecaf225-b11e-49c0-8148-ea2e5693d6bd <- This is a generated v4uuid with no collision anywhere else 
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=MITRE ATT&CK"
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,external-reference-as-report
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_MOBILE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json
      - MITRE_ICS_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/ics-attack/ics-attack.json
      - MITRE_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always
```

Run docker-compose up -d

Get the following error

```
OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
```

The OpenCTI instance is working otherwise
