### ISSUE TITLE
[Hygiene] 5.3.0 - Hygiene connector crashing

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#690]
On 5.3.0 the Hygiene connector is crashing with the following traceback:
![Screen Shot 2022-05-23 at 1 50 56 PM](https://user-images.githubusercontent.com/51339113/169878364-fa66d1de-ca31-4651-bcbd-d67aa1028331.png)

hygiene connector config: 
```
- name: OPENCTI_TOKEN
  value: 
- name: OPENCTI_URL
  value: 
- name: CONNECTOR_ID
  value: 
- name: CONNECTOR_TYPE
  value: INTERNAL_ENRICHMENT
- name: CONNECTOR_NAME
  value: Hygiene
- name: CONNECTOR_SCOPE
  value: 'IPv4-Addr,IPv6-Addr,Domain-Name,StixFile,Artifact'
- name: CONNECTOR_AUTO
  value: 'true'
- name: CONNECTOR_CONFIDENCE_LEVEL
  value: '51'
- name: CONNECTOR_LOG_LEVEL
  value: info
- name: CONNECTOR_UPDATE_EXISTING_DATA
  value: 'False'
- name: HYGIENE_WARNINGLISTS_SLOW_SEARCH
  value: 'False'
- name: HYGIENE_ENRICH_SUBDOMAINS
  value: 'False'
```
