### ISSUE TITLE
[MISP] null state fills rabbitmq 

### ISSUE THREAD

**Issue by Tonnulus** [OpenCTI-Platform/connectors#794]
## Description

The state of Misp connector is always `null` . Every day a lot of new messages fills the rabbitmq. 
There is no error on logs (connector and opencti).
## Environment

1. OS (where OpenCTI server runs):Debian 10.11
2. OpenCTI version: 5.3.7
3. OpenCTI client: frontend 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Stop the connector, clear all work of misp connector, Reset the connector state.  Clear rabbitmq queue
2. Re-start the connector
3. wait for 24h.

## Additional information
Configuration:
```
  connector-misp:
    image: opencti/connector-misp:5.3.7
    environment:
      OPENCTI_URL: http://opencti.:8080/opencti
      OPENCTI_TOKEN: ${OPENCTI_C_MISP_TOKEN}
      CONNECTOR_ID: 42cf4773-e515-4b1b-be9d-859e710725c1
      CONNECTOR_TYPE: EXTERNAL_IMPORT
      CONNECTOR_NAME: MISP
      CONNECTOR_SCOPE: misp
      CONNECTOR_CONFIDENCE_LEVEL: 15 
      CONNECTOR_UPDATE_EXISTING_DATA: "true"
      CONNECTOR_LOG_LEVEL: info
      MISP_URL: https://sec-misp/
      MISP_KEY: ${OPENCTI_MISP_TOKEN}
      MISP_SSL_VERIFY: "False" # Required
      MISP_DATETIME_ATTRIBUTE: timestamp 
      MISP_CREATE_REPORTS: "True" 
      MISP_CREATE_INDICATORS: "True" 
      MISP_CREATE_OBSERVABLES: "True" 
      MISP_CREATE_OBJECT_OBSERVABLES: "True" 
      MISP_REPORT_CLASS: MISP Event 
      MISP_IMPORT_FROM_DATE: "2022-07-03" 
      MISP_IMPORT_DISTRIBUTION_LEVELS: 0,1,2,3
      MISP_IMPORT_THREAT_LEVELS: 1,2,3,4
      MISP_IMPORT_ONLY_PUBLISHED: "True"
      MISP_IMPORT_WITH_ATTACHMENTS: "False"
      MISP_IMPORT_TO_IDS_NO_SCORE: 10
      MISP_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT: "False
      MISP_INTERVAL: 60 

```

## Screenshots (optional)
connector started with MISP_IMPORT_FROM_DATE: "2022-07-03" : 
![image](https://user-images.githubusercontent.com/9503671/185893437-6553375f-190f-4ff5-bd8b-8f8498feb42c.png)
![image](https://user-images.githubusercontent.com/9503671/185895606-f81479d4-a32b-488f-9a52-14327f25f65a.png)

connector started with MISP_IMPORT_FROM_DATE: "2021-01-01" : 
![image](https://user-images.githubusercontent.com/9503671/185894155-ddcacdf5-0cd6-41fe-b230-36dc2de6a18e.png)

**Comment by Tonnulus** [comment]
Hi, I allow myself to re-open this issue because this bug  is back.
![image](https://user-images.githubusercontent.com/9503671/188811521-d3cfd765-7bcd-4368-a710-ad1ff52b67b4.png)
![image](https://user-images.githubusercontent.com/9503671/188811762-4a7df49b-e428-4609-8cd2-321df580335f.png)

The state is good `{"last_run": "2022-09-07T01:33:07"}` But there is task with Operations completed `-` and Total number of operations `-`

Current configuration:
```
  connector-misp:
    image: opencti/connector-misp:5.3.8
    environment:
      OPENCTI_URL: http://opencti.:8080/opencti
      OPENCTI_TOKEN: ${OPENCTI_C_MISP_TOKEN}
      CONNECTOR_ID: 42cf4773-e515-4b1b-be9d-859e710725c1
      CONNECTOR_TYPE: EXTERNAL_IMPORT
      CONNECTOR_NAME: MISP
      CONNECTOR_SCOPE: misp
      CONNECTOR_CONFIDENCE_LEVEL: 15 # From 0 (Unknown) to 100 (Fully trusted)
      CONNECTOR_UPDATE_EXISTING_DATA: "true"
      CONNECTOR_LOG_LEVEL: info
      MISP_URL: https://sec-misp/
      MISP_KEY: ${OPENCTI_MISP_TOKEN}
      MISP_SSL_VERIFY: "False" # Required
      MISP_DATETIME_ATTRIBUTE: timestamp # Required, filter to be used in query for new MISP events
      MISP_CREATE_REPORTS: "True" # Required, create report for MISP event
      MISP_CREATE_INDICATORS: "True" # Required, create indicators from attributes
      MISP_CREATE_OBSERVABLES: "True" # Required, create observables from attributes
      MISP_CREATE_OBJECT_OBSERVABLES: "True" # Required, create text observables for MISP objects
      MISP_REPORT_CLASS: MISP Event # Optional, report_class if creating report for event
      MISP_IMPORT_FROM_DATE: "2022-01-01" # Optional, import all event from this date
      MISP_IMPORT_DISTRIBUTION_LEVELS: 0,1,2,3
      MISP_IMPORT_THREAT_LEVELS: 1,2,3,4
      MISP_IMPORT_ONLY_PUBLISHED: "True"
      MISP_IMPORT_WITH_ATTACHMENTS: "False" # Optional, try to import a PDF file from the attachment attribute
      MISP_IMPORT_TO_IDS_NO_SCORE: 10
      MISP_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT: "False" #  Optional, import unsupported observable as x_opencti_text
      MISP_INTERVAL: 60 # Required, in minutes
    <<: *default_options
```

I tried to stop the docker, to remove the docker, rester the state, remove the rabbitmq queue. remove job. But the bug persists
