### ISSUE TITLE
Observable ignoring confidence level

### ISSUE THREAD

**Issue by micaelalex** [OpenCTI-Platform/connectors#913]
## Environment

1. OS (where OpenCTI server runs): Windows 10 (Docker)
2. OpenCTI version: OpenCTI 5.3.17
3. OpenCTI client: Frontend
4. Other environment details: Connector VirusTotal with confidence 50 and connector AbuseIPDB with confidence 75.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click observations
2. Click +
3. Create IPV4 address observable

## Expected Output

`x_opencti_score` should maintain score from AbuseIPDB

## Actual Output

`x_opencti_score` is being replaced by VirusTotal

## Additional information

```
 connector-abuseipdb:
    image: opencti/connector-abuseipdb:5.3.17
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=#####
      - CONNECTOR_ID=#####
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=AbuseIPDB
      - CONNECTOR_SCOPE=IPv4-Addr
      - CONNECTOR_AUTO=true
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - ABUSEIPDB_API_KEY=#####
      - ABUSEIPDB_MAX_TLP=TLP:AMBER
    restart: always
    depends_on:
      - opencti

  connector-virustotal:
    image: opencti/connector-virustotal:5.3.17
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=#####
      - CONNECTOR_ID=#####
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=VirusTotal
      - CONNECTOR_SCOPE=StixFile,Artifact,IPv4-Addr,Domain-Name,Url
      - CONNECTOR_AUTO=true # Enable/disable auto-enrichment of observables
      - CONNECTOR_CONFIDENCE_LEVEL=50 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - VIRUSTOTAL_TOKEN=#####
      - VIRUSTOTAL_MAX_TLP=TLP:AMBER
      # File/Artifact specific config settings
      - VIRUSTOTAL_FILE_CREATE_NOTE_FULL_REPORT=true # Whether or not to include the full report as a Note
      - VIRUSTOTAL_FILE_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for File/Artifact based observables once this positive theshold is reached. Note: specify 0 to disable indicator creation
      - VIRUSTOTAL_FILE_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
      - VIRUSTOTAL_FILE_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
      # IP specific config settings
      - VIRUSTOTAL_IP_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for IPv4 based observables once this positive theshold is reached. Note: specify 0 to disable indicator creation
      - VIRUSTOTAL_IP_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
      - VIRUSTOTAL_IP_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
      # Domain specific config settings
      - VIRUSTOTAL_DOMAIN_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for Domain based observables once this positive theshold is reached. Note: specify 0 to disable indicator creation
      - VIRUSTOTAL_DOMAIN_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
      - VIRUSTOTAL_DOMAIN_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
      # URL specific config settings
      - VIRUSTOTAL_URL_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for Url based observables once this positive theshold is reached. Note: specify 0 to disable indicator creation
      - VIRUSTOTAL_URL_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
      - VIRUSTOTAL_URL_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/8707982/202235411-3c2ada28-abaf-402a-950e-edba03e4a4d9.png)
