### ISSUE TITLE
Connector listen_routing Error

### ISSUE THREAD

**Issue by mxamusic** [OpenCTI-Platform/connectors#929]
## Prerequisites

- [x] I read the [Deployment and Setup](https://filigran.notion.site/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://filigran.notion.site/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description
I am adding new connector (MISP and MITRE) but I am getting the same error
```
ERROR:root:Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?
{'name': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?', 'message': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?'}
```
```
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Listing Threat-Actors with filters null.
ERROR:root:Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?
Traceback (most recent call last):
  File "/opt/opencti-connector-misp/misp.py", line 2098, in <module>
    mispConnector = Misp()
  File "/opt/opencti-connector-misp/misp.py", line 166, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 571, in __init__
    connector_configuration = self.api.connector.register(self.connector)
  File "/usr/local/lib/python3.10/site-packages/pycti/api/opencti_api_connector.py", line 103, in register
    result = self.api.query(query, connector.to_input())
  File "/usr/local/lib/python3.10/site-packages/pycti/api/opencti_api_client.py", line 328, in query
    raise ValueError(
ValueError: {'name': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?', 'message': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?'}
Killed
```
here is the docker configuration
```yml
connector-misp:
    image: opencti/connector-misp:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=4d976a6f-d457-4471-9f4a-707299cfeddc
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=https://192.168.70.2 # Required
      - MISP_KEY=i2OnAQTQRzca2ND6KV8fgBnkK6c9uCrtMBMR34Xr # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_REPORT_CLASS=MISP event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always
    depends_on:
      - opencti
  connector-mitre:
    image: opencti/connector-mitre:5.4.1
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=afa79352-1ae3-4949-99a1-0c21c21e5009
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE Datasets
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,external-reference-as-report
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack.json
      - MITRE_MOBILE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/mobile-attack/mobile-attack.json
      - MITRE_ICS_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/ics-attack/ics-attack.json
      - MITRE_CAPEC_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/capec/2.1/stix-capec.json
      - MITRE_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always
    depends_on:
      - opencti
 ```
## Environment

1) OpenCTI VM Template
2) MISP VM Template 

## Reproducible Steps

Just Add the container with settings above and I get the error. 
## Additional information

![image](https://user-images.githubusercontent.com/16447622/203635118-b63caa5b-d46f-432f-bb0f-bf65a24ab21a.png)
![image](https://user-images.githubusercontent.com/16447622/203635236-29e6044d-65c5-4707-b88e-943df1be5fa8.png)
