### ISSUE TITLE
MISP Connector - No publication created

### ISSUE THREAD

**Issue by Rominov** [OpenCTI-Platform/connectors#93]
##  Description

I created a MISP Event called "toto". In my docker-compose-yml, i correctly added the opencti-connector lines. The indicators are correctly imported on OpenCTI but there is no publication linked to all this indicators (12k5 IoC's). 

Secondly, If my publication in obsolete in MISP. Can i mark my IoC's obsolete if  they are in a publication ?

## Environment

1. OS : Debian 10
2. OpenCTI version: 3.1.0 -  Docker-compose
3. VMWare ESXi 6.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Config file : 
```
connector-misp:
    image: opencti/connector-misp:3.1.0
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MISP_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=https://X.X.200.114 # Required
      - MISP_KEY=XXXXXXXXXXXX #Hidden but correctly entered
      - MISP_SSL_VERIFY=False # Required
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      - MISP_INTERVAL=180 # Required, in minutes
    restart: always
```
## Expected Output

I exepect to have a report related to my MISP Event named "toto" to contains all my IoC's

## Actual Output

Got my IoC's correctly imported with no reports linked to my IoC's
connector-misp_1                         | INFO:root:MISP returned 1 events.
