### ISSUE TITLE
[MWDB] Disabling SSL Verification

### ISSUE THREAD

**Issue by gregorygui** [OpenCTI-Platform/connectors#935]
## Description

Allow OpenCTI to pull data from MWDB without SSL verification.

## Environment

1. Debian 11
2. OpenCTI version: OpenCTI 5.4.1
3. OpenCTI client: OpenCTI 5.4.1
4. MWDB Connector: 5.4.1

## Reproducible Steps

Use a self-signed or internal SSL certificate for the MWDB instance leads to
```
ERROR:root:HTTPSConnectionPool(host='<REDACTED>', port=443): Max retries exceeded with url: /api/file?query=upload_time:%5B2022-05-28%20TO%20%2A%5D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```

## Expected Output

Allow SSL verification to be disabled via a configuration setting. Default should be verification enabled.

## Proposed modification

src/mwdb.py
```python
# line 50 - add a line with
self.mwdb_check_ssl = get_config_variable("MWDB_CHECK_SSL", ["mwdb", "check_ssl"], config, False, True)
[...]
# line 556 add verify option to request
resp = requests.get(self.mwdb_url + search_path, headers=auth, verify=self.mwdb_check_ssl)
```

config.yml.sample
```yaml
opencti:
  url: 'http://opencti:8080'
  token: 'ChangeMe'

connector:
  id: 'ChangeMe'
  type: 'EXTERNAL_IMPORT'
  name: 'MWDB Artifacts'
  scope: 'mwdb'
  log_level: 'info'

mwdb:
  url: 'ChangeMe'
  confidence_level: 60 # From 0 (Unknown) to 100 (Fully trusted)
  create_indicators: True
  create_observables: True
  interval: 3 # In days, must be strictly greater than 1
  update_existing_data: True
  token: 'ChangeMe'
  import_config: True
  start_date: '2022-04-01T00:00:00'  # ISO 8601
  org_description: 'ChangeMe'
  org_name: 'ChangeMe'
  start_date: '2022-04-01T00:00:00'
  tag_filter: 'virusshare.*|bazaar-.*|malshare-.*|apt20\d{2}'
  start_retention: 5
  check_ssl: true
  ```
