### ISSUE TITLE
[MWDB] ERROR:root:nothing to repeat at position 0

### ISSUE THREAD

**Issue by V1D1AN** [OpenCTI-Platform/connectors#981]
## Description

The connection between the connector-mwdb and mwdb don't work correctly.
I have an error when I start my docker connector-mwdb.
```
ERROR:root:nothing to repeat at position 0
```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.1
2. OpenCTI version: 5.5.2
3. OpenCTI client: Frontend
4. Other environment details: Environment on docker.

## Actual Output

```

                              MWDB Connector, version 5.5.2

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 4e154e0d-b393-459e-87e4-009b768a2c55
INFO:root:Starting ping alive thread
INFO:root:Creating Identity {S1EM}.
INFO:root:Fetching MWDB dataset...
INFO:root:Creating Label {C2}.
INFO:root:Creating Label {C2 LIST}.
INFO:root:Initiate work for 4e154e0d-b393-459e-87e4-009b768a2c55
INFO:root:Connector has never run
INFO:root:Connector will run!
INFO:root:Creating External Reference {S1EM url ref}.
ERROR:root:nothing to repeat at position 0

```

## Additional information

A part of my docker-compose.yml :
```
  connector-mwdb:
    image: opencti/connector-mwdb:latest
    container_name: connector-mwdb
    hostname: connector-mwdb
    environment:
      - OPENCTI_URL=http://opencti:8080/opencti
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MWDB_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MWDB connector
      - CONNECTOR_SCOPE=mwdb
      - CONNECTOR_LOG_LEVEL=info
      - MWDB_URL=http://mwdb-web/
      - MWDB_CONFIDENCE_LEVEL=40 # From 0 (Unknown) to 100 (Fully trusted)
      - MWDB_INTERVAL=1 # In days, must be strictly greater than 1
      - MWDB_TOKEN=${MWDB_API}
      - MWDB_IMPORT_CONFIG=True
      - MWDB_CREATE_INDICATORS=True
      - MWDB_CREATE_OBSERVABLES=True
      - MWDB_UPDATE_EXISTING_DATA=True
      - MWDB_ORG_DESCRIPTION=Cyber
      - MWDB_ORG_NAME=${ORGANIZATION}
      - MWDB_START_DATE=2023-01-01T00:00:00.000Z  # ISO 8601
      - MWDB_TAG_FILTER=*
      - MWDB_MAX_START_RETENTION=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - s1em
```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/18678787/213009476-26d1c7f6-af86-4ebc-9867-309e514a0ddd.png)

![image](https://user-images.githubusercontent.com/18678787/213009575-1838dc8f-3908-4699-8f6e-2e11aa86c59f.png)
